name: CI

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  typecheck:
    name: Typecheck
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: latest

      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Typecheck
        run: pnpm typecheck

  test-build:
    name: Test build
    runs-on: ubuntu-latest
    env:
      ALGOLIA_APP_ID: ${{secrets.ALGOLIA_APP_ID}}
      ALGOLIA_INDEX_NAME: ${{secrets.ALGOLIA_INDEX_NAME}}
      ALGOLIA_SEARCH_API_KEY: ${{secrets.ALGOLIA_SEARCH_API_KEY}}

    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: latest

      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Test build
        run: pnpm build
